In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
casual_df=pd.read_csv('Casualties0514.csv')
accident_df=pd.read_csv('Accidents0514.csv')
vehicle_df=pd.read_csv('Vehicles0514.csv')

C:\Users\vignesh kumar\AppData\Local\Temp\ipykernel_13624\3558190798.py:2: DtypeWarning: Columns (31) have mixed types. Specify dtype option on import or set low_memory=False.
  accident_df=pd.read_csv('Accidents0514.csv')


In [4]:
first_df=pd.merge(casual_df,accident_df,on='Accident_Index')

In [5]:
df=pd.merge(first_df,vehicle_df,on='Accident_Index')

In [6]:
df.drop('LSOA_of_Accident_Location',axis=1,inplace=True)


In [7]:
df.dropna(subset=['Time'],axis=0,inplace=True)
df

Accident_Index  Vehicle_Reference_x  Casualty_Reference  \
0        200501BS00001                    1                   1   
1        200501BS00002                    1                   1   
2        200501BS00003                    2                   1   
3        200501BS00003                    2                   1   
4        200501BS00004                    1                   1   
...                ...                  ...                 ...   
4287588  2014984138414                    2                   2   
4287589  2014984139614                    1                   2   
4287590  2014984139614                    1                   2   
4287591  2014984139614                    2                   1   
4287592  2014984139614                    2                   1   

         Casualty_Class  Sex_of_Casualty  Age_of_Casualty  \
0                     3                1               37   
1                     2                1               37   
2                     1                1               62   
3                     1                1               62   
4                     3                1               30   
...                 ...              ...              ...   
4287588               1                1               44   
4287589               2                1               61   
4287590               2                1               61   
4287591               1                1               79   
4287592               1                1               79   

         Age_Band_of_Casualty  Casualty_Severity  Pedestrian_Location  \
0                           7                  2                    1   
1                           7                  3                    0   
2                           9                  3                    0   
3                           9                  3                    0   
4                           6                  3                    5   
...                       ...                ...                  ...   
4287588                     7                  2                    0   
4287589                     9                  3                    0   
4287590                     9                  3                    0   
4287591                    11                  3                    0   
4287592                    11                  3                    0   

         Pedestrian_Movement  ...  Was_Vehicle_Left_Hand_Drive?  \
0                          1  ...                             1   
1                          0  ...                             1   
2                          0  ...                             1   
3                          0  ...                             1   
4                          2  ...                             1   
...                      ...  ...                           ...   
4287588                    0  ...                             1   
4287589                    0  ...                             1   
4287590                    0  ...                             1   
4287591                    0  ...                             1   
4287592                    0  ...                             1   

         Journey_Purpose_of_Driver  Sex_of_Driver  Age_of_Driver  \
0                               15              2             74   
1                                1              1             42   
2                                1              1             35   
3                               15              1             62   
4                               15              2             49   
...                            ...            ...            ...   
4287588                          6              1             73   
4287589                          1              1             40   
4287590                          6              1             79   
4287591                          1              1             40   
4287592                          6      

In [8]:
df.isnull().values.any()

True

In [9]:
df.dropna(inplace=True)


In [10]:
df.isnull().values.any()
df.columns

Index(['Accident_Index', 'Vehicle_Reference_x', 'Casualty_Reference',
       'Casualty_Class', 'Sex_of_Casualty', 'Age_of_Casualty',
       'Age_Band_of_Casualty', 'Casualty_Severity', 'Pedestrian_Location',
       'Pedestrian_Movement', 'Car_Passenger', 'Bus_or_Coach_Passenger',
       'Pedestrian_Road_Maintenance_Worker', 'Casualty_Type',
       'Casualty_Home_Area_Type', 'Location_Easting_OSGR',
       'Location_Northing_OSGR', 'Longitude', 'Latitude', 'Police_Force',
       'Accident_Severity', 'Number_of_Vehicles', 'Number_of_Casualties',
       'Date', 'Day_of_Week', 'Time', 'Local_Authority_(District)',
       'Local_Authority_(Highway)', '1st_Road_Class', '1st_Road_Number',
       'Road_Type', 'Speed_limit', 'Junction_Detail', 'Junction_Control',
       '2nd_Road_Class', '2nd_Road_Number',
       'Pedestrian_Crossing-Human_Control',
       'Pedestrian_Crossing-Physical_Facilities', 'Light_Conditions',
       'Weather_Conditions', 'Road_Surface_Conditions',
       'Special_Condi

In [11]:
q3_df=pd.DataFrame(data=df,columns=['Longitude','Latitude','1st_Road_Class','2nd_Road_Class','Weather_Conditions'])

In [12]:
q3_df

Longitude   Latitude  1st_Road_Class  2nd_Road_Class  \
0        -0.191170  51.489096               3              -1   
1        -0.211708  51.520075               4               5   
2        -0.206458  51.525301               5              -1   
3        -0.206458  51.525301               5              -1   
4        -0.173862  51.482442               3              -1   
...            ...        ...             ...             ...   
4287588  -3.191397  54.990446               3               5   
4287589  -3.348426  55.106700               4               4   
4287590  -3.348426  55.106700               4               4   
4287591  -3.348426  55.106700               4               4   
4287592  -3.348426  55.106700               4               4   

         Weather_Conditions  
0                         2  
1                         1  
2                         1  
3                         1  
4                         1  
...                     ...  
4287588                   2  
4287589                   1  
4287590                   1  
4287591                   1  
4287592                   1  

[4287073 rows x 5 columns]

In [13]:
X=q3_df.drop('Weather_Conditions',axis=1)
y=q3_df['Weather_Conditions']

q3_df['Weather_Conditions'].unique()

array([ 2,  1,  9,  3,  8,  4,  5,  7,  6, -1], dtype=int64)

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test= train_test_split(X,y)
X_train.head(20)


Longitude   Latitude  1st_Road_Class  2nd_Road_Class
632107   -2.214955  53.562116               6               6
481305   -3.219214  51.516491               6              -1
382650   -0.533446  51.272391               6              -1
3539223  -3.323935  55.939551               3               6
2121679  -1.854047  52.435764               6               6
1466579  -3.816439  51.660196               3               3
225546   -2.194608  53.008433               3               6
428113   -4.125922  51.072150               4               6
3670245  -1.453349  53.808468               3               6
2242333  -0.637721  51.522290               6               6
2695323  -0.776953  50.868627               5              -1
4210100  -0.446016  50.819093               6               6
3409592  -0.255937  51.663901               5               6
3773442   0.500594  51.586264               6               6
4192410  -0.556472  51.307551               3               6
917133   -0.193795  51.100911               3               3
2570707  -1.463034  52.522829               3              -1
3464095   0.239320  51.434629               3               6
3688361  -2.122882  52.573429               3              -1
3314543  -0.457479  53.683895               3              -1

In [16]:
from sklearn.tree import DecisionTreeClassifier

In [17]:
dtree= DecisionTreeClassifier()

In [18]:
dtree.fit(X_train.values,y_train.values)

DecisionTreeClassifier()

In [19]:
predictions= dtree.predict(X_test.values)

In [20]:
from sklearn.metrics import classification_report, confusion_matrix

In [21]:
print(classification_report(y_test.values,predictions))

              precision    recall  f1-score   support

          -1       0.68      0.72      0.70       101
           1       0.93      0.95      0.94    852363
           2       0.77      0.72      0.74    131187
           3       0.75      0.69      0.72      7514
           4       0.75      0.68      0.71     13676
           5       0.75      0.69      0.72     15480
           6       0.76      0.73      0.74      1390
           7       0.82      0.77      0.79      8022
           8       0.74      0.67      0.70     23479
           9       0.73      0.65      0.69     18557

    accuracy                           0.90   1071769
   macro avg       0.77      0.73      0.75   1071769
weighted avg       0.90      0.90      0.90   1071769



In [22]:
print(confusion_matrix(y_test.values,predictions))
q3_df

[[    73     24      3      0      1      0      0      0      0      0]
 [    26 812032  24466   1337   2435   2732    237   1071   4402   3625]
 [     5  34375  94235    203    406    464     37    190    730    542]
 [     0   1859    272   5206     35     37     10     16     48     31]
 [     0   3654    483     33   9278     54      9     17     79     69]
 [     0   3911    646     34     45  10650     10     17     98     69]
 [     2    270     47     11      9     13   1013      3     17      5]
 [     0   1530    194     14     32     13      5   6170     40     24]
 [     0   6543    893     38    120     98      8     43  15617    119]
 [     1   5542    652     26     81     77      7     34    112  12025]]


Longitude   Latitude  1st_Road_Class  2nd_Road_Class  \
0        -0.191170  51.489096               3              -1   
1        -0.211708  51.520075               4               5   
2        -0.206458  51.525301               5              -1   
3        -0.206458  51.525301               5              -1   
4        -0.173862  51.482442               3              -1   
...            ...        ...             ...             ...   
4287588  -3.191397  54.990446               3               5   
4287589  -3.348426  55.106700               4               4   
4287590  -3.348426  55.106700               4               4   
4287591  -3.348426  55.106700               4               4   
4287592  -3.348426  55.106700               4               4   

         Weather_Conditions  
0                         2  
1                         1  
2                         1  
3                         1  
4                         1  
...                     ...  
4287588                   2  
4287589                   1  
4287590                   1  
4287591                   1  
4287592                   1  

[4287073 rows x 5 columns]

In [23]:
import pickle
pickle.dump(dtree, open("whether.pkl", "wb"))